### ISSUE TITLE
Serializing cart object in Flask session variable

### ISSUE THREAD

**Issue by wgwz** [mirumee/satchless#150]
I've noticed Saleor has a cart that can be serialized. https://github.com/mirumee/saleor/blob/master/saleor/cart/__init__.py#L131 (I haven't figure out how it works...)

Currently, doing something like this is Flask:

    @app.route('/')
    def index():
        if session.get('cart') is None:
            session['cart'] = Cart()
        return render_template('index.html')

Results in an error something like object is not JSON-serializable. It would be awesome if this method worked, and I could add stuff to the cart as `session['cart'].add(...)`. I am relatively new to Python, so I don't know how to tackle this problem. Advice appreciated.

**Comment by patrys** [comment]
Saleor has a special session cart for this purpose but I think we could try to make it generic enough to fit in satchless.

**Comment by wgwz** [comment]
I did find a way to work around this. But it is quite awkward. I'm going to try to work on this and find a solution. I think it might be able to be solved just by properly configuring the JSONEncoder in Flask.
