### ISSUE TITLE
Prices 1.0

### ISSUE THREAD

**Issue by mjtamlyn** [mirumee/satchless#154]
Hi!

Are there any known compatibility issues with `prices` at version 1? If not, is there any chance a release could be made which removes the requirement for `prices<0.6a1`?

Thanks! ✨

**Comment by rafalp** [comment]
Hey Marc!

`prices 1.0.0` is breaking release as it's complete rewrite of library codebase. We are slowly updating other libraries depending on it to current versions, however as we moved away from Satchless in Saleor, updating it is not priority for us at the moment.

PR is welcome. Giving our code quick skim it seems that `prices` usage in the lib is limited to 3 files in addition to docs and readme, so cooking up update to py3k and `prices` 1.0.0 shouldn't be large undertaking.

I'll be more than happy to offer pointers and answer questions if such PR appears.

Thanks!

**Comment by k5jj** [comment]
Looking at the changes in `prices 1.0.0`....  It appears that `Price` has changed to `Money` and/or `TaxedMoney`, and `PriceRange` has changed to `MoneyRange` and/or `TaxedRange`.    Is this correct?  If so, which is to be used for `satchless`?  My first thought is that the non-Taxed Money would be used?

**Comment by rafalp** [comment]
Looking at what happened in Saleor, it should be assumed that `get_price_per_item()` returns `TaxedMoney()` and `TaxedMoneyRange` should be used for prices ranges.

`TaxedMoney()` is not one to one replacement for old `Price()`, but it contains separate net and gross values that in turn support more use cases, namely ecommerce that uses taxes. If you don't, you may naively convert `Money()` to `TaxedMoney()` via `TaxedMoney(net=Money(), gross=Money())`

Or perhaps we could have `Item` and `TaxedItem`? But that feels like needlessly multiplying number of entities in our API by two, bumping maintenance burden somewhat and asking about possible mixing of both in your project. (cc @patrys?)
