### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by dsoprea** [mirumee/satchless#161]
Is there a demo of Satchless, or even a set of screenshots, somewhere?

**Comment by patrys** [comment]
Satchless is a library; there is no user interface. You may be looking for [Saleor](https://saleor.io/) instead?

**Comment by dsoprea** [comment]
Sure. I didn't realize that it was the same team. The description of this project is "Ecommerce for Python",  which implies a UI, not a library, which is then not-helped by the lack of any further description about what this project is.

Thanks.

**Comment by dsoprea** [comment]
#162
