### ISSUE TITLE
Expand the description of this project

### ISSUE THREAD

**Issue by dsoprea** [mirumee/satchless#162]
This project is opensource and has a good number of stars and yet there's no description of what it does or how it can be used. As I understand it, it's a library. For what purpose? 

There's no point in making something open-source but keeping it a secret.

**Comment by rafalp** [comment]
Would copying the introduction from docs to readme help here?:

> Overview
>
> Satchless is a low-level library that provides base classes, interfaces and patterns to work with while implementing a store. Its goal is to provide you with well-tested core logic to build business logic and UIs upon.
>
>Satchless **is not a framework** and it will not give you a full-fledged store to work with. If that is what you want and you’re working with Django, check the Saleor project instead.

**Comment by dsoprea** [comment]
Yes. Exactly.

Thanks.

**Comment by 0proboy0** [comment]
> Yes. Exactly.
> 
> Thanks.

#163

**Comment by NyanKiyoshi** [comment]
Thank you for the change @0proboy0 👍
